### ISSUE TITLE
small fix if its not intentional about Agglomeration

### ISSUE THREAD

**Issue by ovelol** [glisco03/things#100]
if possible, Id like to propose the Agglomeration be undoable so you can recombine it with other Trinkets, or allow the player to change the Effects or Cosmetic to still be changeable once you agglomerated two things with different buttons since it says right click on both but it only changes the top Trinket.

**Comment by gliscowo** [comment]
You can (or at least, should be able to) change which trinket is affected by right-click actions and so-forth by scrolling on the Agglomeration in your inventory. If that doesn't work, reopen the issue so we can look into why

Cheers
