### ISSUE TITLE
running shoes and bunny hopper's not working together.

### ISSUE THREAD

**Issue by johnuvm** [glisco03/things#101]
I combined the running shoes and the bunny hoppers to the empty agglomeration and while it still kept the bunny hopper's ability of no fall damage, I no longer have the jump boost from it nor any of the running shoes abilities.

**Comment by Aesthir** [comment]
This is a problem with anything placed into an agglomeration. Using an agglomeration bricks the trinkets in 1.21.

**Comment by Dragon-Seeker** [comment]
Accessories builtin API for such has bugs that prevent some features of such to not work and issues within Accessories TCLayer would be the cause of Artifacts not working.

**Comment by Dragon-Seeker** [comment]
An update will be come out coming up

**Comment by gliscowo** [comment]
Seeing as this not a Things problem, I'll be closing this issue

Cheers
