### ISSUE TITLE
[Compatibility] Fabric 1.20.1 Missing JEI support

### ISSUE THREAD

**Issue by Cicopath** [glisco03/things#102]
Fabric 0.16.3+1.20.1
Things 0.3.3

The recipe for the broken watch is not displaying whatsoever.

1. Install the latest versions of JEI & Things for Fabric
2. Try to view the recipe for Broken Watch

**Comment by BasiqueEvangelist** [comment]
I don't think we have (or plan to?) add support for JEI? It should work in REI, which [we have explicit support for.](https://github.com/wisp-forest/things/blob/1.20/src/main/java/com/glisco/things/compat/rei/ThingsPlugin.java)

**Comment by Cicopath** [comment]
Yeah it works with REI, which is why I was confused when I didn't see the recipe with JEI. I didn't know whether compatibility was missing (a bug) or no support was provided for it.

Out of curiosity, how come there are no plans to add support for JEI?

**Comment by gliscowo** [comment]
Neither me nor anyone else on the team has any interest in spending any of their limited time on maintaining more than one recipe viewer integration. Even if so, we would likely add support for [EMI](https://modrinth.com/mod/emi) instead, seeing as it can also display recipes from mods with JEI integration

Cheers

**Comment by Cicopath** [comment]
I don't understand why there would be no support for JEI, objectively the most downloaded recipe viewer mod with almost 10 times more downloads than REI, let alone being the mod with _the most downloads_ ever.

Regardless... I hope that you, the Things dev team, can support either JEI or EMI some time in the future. EMI can see JEI recipes if the latter mod is installed, while EMI has additional functionalities. On another note, I also had to switch from REI due to the lag it presents and common issues which hindered gameplay.

It would be beneficial to support at least one other recipe viewer to expand which recipe viewer mods players can choose from rather than having to choose based on whether players can see the special broken watch recipe

I would add a pull request for JEI or EMI, but I'm not familiar enough with modding and coding in Java to do so.

**Comment by BasiqueEvangelist** [comment]
> I don't understand why there would be no support for JEI, objectively the most downloaded recipe viewer mod with almost 10 times more downloads than REI, let alone being the mod with _the most downloads_ ever.

Well, the main reason only REI is supported is because it was the main recipe viewer mod *on Fabric* for a long time, and we don't really see any point in adding support for JEI when most people just use REI or EMI instead. ~~and we also just prefer REI over EMI anyways~~

Making a pull request for EMI support would be nice, though I don't know if it'd be merged, since it would effectively then be glisco's burden to maintain it. Regardless, you (or whoever picks this up) could make a separate addon that adds EMI support for Things.
