### ISSUE TITLE
Diamond picaxe doesnt break gleaming ore

### ISSUE THREAD

**Issue by Lumb3rSamur4i** [glisco03/things#108]
As the title says
![image](https://github.com/user-attachments/assets/123d7ffa-79d5-404b-8140-6efac4751bf0)
It just gives me experience
![image](https://github.com/user-attachments/assets/51749fed-a4b5-45f4-818e-c6098efc52d1)

**Comment by Lumb3rSamur4i** [comment]
The picaxe has this enchantments

![image](https://github.com/user-attachments/assets/acd90418-e4d0-4963-828e-43ab6d629c99)

**Comment by Dragon-Seeker** [comment]
#104 PR should fix this issue as it is an issue with 1.21 format change for loot table

**Comment by gliscowo** [comment]
The above-mentioned fix (or rather, a fixed version of the fix 😂) has now been released in [0.4.2](https://modrinth.com/mod/things/version/0.4.2+1.21) - thanks for reporting

Cheers
