### ISSUE TITLE
Gleaming Ore stays as Ore block after mined with enchanted pickaxe

### ISSUE THREAD

**Issue by SVEI-1** [glisco03/things#109]
I came across this problem a few hours ago and saw that with the 0.4.1 fix, it should work. It does work with a unenchanted pickaxe but dosen't with a enchanted one. Not sure if it didnt work with either one befor the fix.

**Comment by gliscowo** [comment]
Please use [0.4.2](https://modrinth.com/mod/VzAGdu9D/version/C9vVXLgu) instead and ignore that 0.4.1 ever happened. In fact, I don't even know what release you're talking about :clueless:

Cheers

**Comment by SVEI-1** [comment]
0.4.1? Ur right that donst exist. What was i thinking? ;)

p.s thx <3
