### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by WillTheWanted** [glisco03/things#11]
Ive tried adding this mod to my Minecraft server on Pebble Hosting and for some reason it isn't compatible.

Ive already talked with the staff of the website but they are not sure what's wrong either and told me to contact the mod dev.
The server is fabric 1.17.1
I don't know what's going on.

**Comment by gliscowo** [comment]
Without a log or crash report it is basically impossible for me to provide help. Providing either the latest.log file from right after a crash or the appropriate crash report would be good 
Cheers

**Comment by gliscowo** [comment]
As you have not yet provided any further information since and the 1.17 version is not being actively maintained anymore, I will go ahead and mark this issue resolved for now
