### ISSUE TITLE
Adds a configurable GleamingOre generation probability

### ISSUE THREAD

**Issue by mcmaidong** [glisco03/things#112]
GleamingOre is so rare that I couldn't find it and it would be nice to have a configurable option

**Comment by gliscowo** [comment]
Ore Generation has long been controlled by datapacks and not code. As such, this would not only be somewhat complex to implement but also pointless - this can already be accomplished by making an appropriate datapack which overrides the respective features from Things - contact us if you'd like help with creating such a datapack.

On a different note, where did you search for it? If you go caving between -15 and 15 (about the height range where Stone and Deepslate meet, as the Almanac explains) it's genuinely rather common

Cheers
