### ISSUE TITLE
Mining gleaming ore

### ISSUE THREAD

**Issue by Denomaki** [glisco03/things#13]
Hi,

I'd like to ask you a question. It might very well be just me, but when I'm playing MC with this mod and I find gleaming ore, there is no way I can mine it with any pickaxe. I have even tried silk touch pickaxes and they don't work either. Every time I try to mine it, the ore just breaks and nothing drops. 
Would you be so kind to give me an advice or tell me what am I doing wrong?
Thank you in advance.

**Comment by gliscowo** [comment]
Are you playing a modpack, and if yes, which one? I would guess this is a compatibility issue as I have never heard of it before and I can mine the ore perfectly fine in dev

**Comment by Denomaki** [comment]
Yes, I am playing it on a modpack - it is a modpack from a youtuber RyanNotBriann from his 100 days series.

**Comment by gliscowo** [comment]
Could you test this again on the latest version? Nobody has since reported any issue with mining the ore, so for now I'll close this issue as it does not seem relevant anymore
