### ISSUE TITLE
Mild incompatibility with "Basic Shields [Fabric]"

### ISSUE THREAD

**Issue by J-0-E-L** [glisco03/things#19]
Retribution enchantment cannot be applied to shield variants.

https://modrinth.com/mod/basic-shields-fabric

**Comment by gliscowo** [comment]
I'll see what I can do for adding compat, as Fabric Shield Lib does not use vanilla's ShieldItem, making it very difficult to correctly detect a shield without directly depending on it. They might have a mechanism I'm not aware of, but we'll have to see

**Comment by gliscowo** [comment]
Fixed in e9d1895
