### ISSUE TITLE
Brewing recipe for Recall Potion does not show up in REI

### ISSUE THREAD

**Issue by J-0-E-L** [glisco03/things#20]
REI does not show any recipe for the recall potion despite it being brew-able.
Given that REI is very popular I'm assuming it's a problem with Things... though this might not be the case.

**Comment by gliscowo** [comment]
This has been a know problem for quite a while, I just sadly never got around to fixing it. It's already done in dev however, scheduled for next release
Cheers

**Comment by gliscowo** [comment]
Fixed in e9d1895
