### ISSUE TITLE
[config] option to turn off terrain generation changes (gleaming ore)

### ISSUE THREAD

**Issue by yesn0t** [glisco03/things#25]
Hi, i'd love to try this mod, and wish i could load my worlds without generating gleaming ore (and any other changes i'm unaware of ?)  
I hope you consider it x)

**Comment by Noaaan** [comment]
Why do you want to disable gleaming ore? Most if not all of the items use it in their crafting recipes

**Comment by yesn0t** [comment]
i would add an alternative recipe to craft gleaming ore or powder using vanilla items,  
i prefer a semi-vanilla playstyle with mostly clientside features, my goal is to make it so when i remove the mod my worlds don't break ^^' or is it a misconception of mine ?

**Comment by Noaaan** [comment]
That seems like a perfectly valid use-case. I will poke glisco about it

**Comment by gliscowo** [comment]
Sorry for taking so long, but this option has finally been added in version [0.2.15](https://github.com/gliscowo/things/releases/tag/0.2.16%2B1.18)
Cheers

**Comment by yesn0t** [comment]
thank you !
