### ISSUE TITLE
Hades Crystal should be more expensive

### ISSUE THREAD

**Issue by Janfel** [glisco03/things#29]
The recipe for the hades crystal currently requires

- 8 Gleaming Powder (Mining)
- 2 Diamonds (Mining)
- 5 Magma Blocks (Ruined portals or underwater caves)
- 2 Magma Cream (Magma cubes or crafting slime balls with blaze powder)

This means that a hades crystal can be crafted shortly after the player has entered the Nether, before they have even found a fortress. This makes the hades crystal obtainable earlier than the mining gloves, riot gauntlet, and even just blaze rods.

The ability of the hades crystal, permanent fire resistance, seems far too powerful for something that is obtainable so early in the game. It takes away the main danger of Nether exploration, before the player ever actually has to explore the Nether.

It also makes some more balanced rewards by other mods basically useless. The mod AdventureZ for example adds a “Nether Beacon” of sorts that gives fire resistance among other effects, and a post-netherite armor set that gives fire resistance on a cooldown. These additions are way less valuable with the hades crystal being so easy to obtain.

I think that the recipe for the hades crystal should require a nether star, like the hardening catalyst, or at least some netherite ingots. I don’t see why the hades crystal should not be locked behind netherite, while the mining gloves, infernal scepter, etc. are.

**Comment by Noaaan** [comment]
As most of the trinkets in Things, the Hades Crystal is definitely powerful for it's price. The main point of the trinket is to save you having to craft fire resistance potions. One magma cream is able to net you up to 24 minutes of fire resistance. To me the fact that the trinket uses two of them means that the point of the item is for convenience. 
You are right in theory where a player can skip one stage of progression by rushing for the trinket. If you try farming for magma cream you can in theory skip having to obtain blaze rods for blaze powder, which you normally would use in a brewing stand. 
I think simply adding blaze rods to the recipe would be sufficient for balancing the item. You would then be forced to aquire most of the materials you need to practically make endless fire resistance.

**Comment by Janfel** [comment]
I understand the convenience aspect in regards to the monocle and the enchanted wax gland, but I think that fire resistance should be handled more like the strength effect (riot gauntlet) and less like night vision, because of it’s enormous defensive value.
It makes the player immune to lava and almost all fire-based attacks, turning the Nether from a dangerous wasteland into a sort of swimming pool. I don’t think that is comparable to night vision or even haste.
With potions, you still have a time limit and the “Oh shit where’s my potion” moment when falling or digging into lava, keeping at least some of the challenge of Nether traversal.
Adding blaze rods would make it so the player has to fight at least *some* blazes before their fireballs become meaningless to them, but I would still prefer if the player had to first “beat the Nether” by killing a wither before they obtain this power.

**Comment by gliscowo** [comment]
Hey, thanks for bringing this issue up. I certainly agree with you that in it's current state the crystal is quite overpowered but I also believe that gating it behind the wither takes away a lot of its appeal. I will go ahead and change the recipe to include blaze rods but I likely won't make it any more expensive. In the end, the balancing decisions are on me and my team to make and we deem that solution perfectly reasonable. If you still want something more expensive, I can only recommend changing the recipe yourself, there are plenty of ways to achieve this.
Have a great day
