### ISSUE TITLE
Leaving the End with socks equipped reduces base player speed

### ISSUE THREAD

**Issue by McGodMan** [glisco03/things#30]
The bug:
When leaving the End dimension through the bedrock portal while wearing socks (of any kind), the players base speed is reduced by the same amount that the socks would normally increase it by.

Steps to reproduce:
1. Enter the End
2. Equip Socks (the faster socks are more noticeable)
3. Leave the End through the bedrock portal
4. Unequip Socks
5. Notice the speed difference

Steps to prevent/fix:
1. Enter the End
2. Unequip Socks
3. Leave the End through the Bedrock Portal

Extra notes:
1. Bug is present even when all other mods are removed (excluding dependencies)
2. Bug does not occur when leaving the End through either dying or commands
3. Entering an Overworld end portal does not cause the bug to occur
4. Manually correcting the players base movement speed does nothing as equipping the socks again returns it to the reduced value (it also changes the fov to the same degree a speed potion would)

**Comment by gliscowo** [comment]
Fixed in 0.2.17, thank you for reporting
Cheers
