### ISSUE TITLE
[Suggestion] Make locked chests indestructible.

### ISSUE THREAD

**Issue by TheAyes** [glisco03/things#35]
Probably self-explanatory but yea what's the point of locking a chest if you still can just break it. :)
Oh maybe add a config entry for it too so people are free to disable if they don't like.

**Comment by gliscowo** [comment]
I just this implemented as a config option in 446ae05 and 3297dce, it'll almost definitely be included in the next update
Cheers

**Comment by gliscowo** [comment]
From version [0.2.18](https://modrinth.com/mod/things/version/0.2.18+1.18) onwards, this is now available via a config option
Cheers
