### ISSUE TITLE
[Feature Request/Question] Off Hand Glove Slot

### ISSUE THREAD

**Issue by saintsareprey** [glisco03/things#38]
I can't put any Gloves items in the offhand glove slot, is this intended for balance purposes and I should just accept it as it is, or is there any way to config them to be placeable there?

**Comment by gliscowo** [comment]
You are in fact correct that this is an intended balancing act. We however won't stop you from allowing it yourself, as Trinkets is configured through datapacks - so you can easily change it. You can read up a little on how the data format works [in their wiki](https://github.com/emilyploszaj/trinkets/wiki/Trinkets-Data-Formats), but in the end you simply need to add the items you want to the `trinkets:offhand/glove` tag. In case you're not familiar, the process of creating a datapack as well as tags is outlined [in this article](https://github.com/LordDeatHunter/Alloy-Forgery/wiki/Datapack-Tutorial).
Cheers

**Comment by saintsareprey** [comment]
Thank you for the information and instructions :D
