### ISSUE TITLE
Mining glove incompatibility 

### ISSUE THREAD

**Issue by deadspidervenom** [glisco03/things#4]
Playing with the origins mods, my origin gives me hast 3, i put the gloves on and it only makes the icon for haste appear, not actual benefit. This may be the case with other "things" items.

**Comment by glisco03** [comment]
Well the mining glove gives you Haste II. So if you already have Haste III, obviously nothing's gonna happen.

**Comment by deadspidervenom** [comment]
> Well the mining glove gives you Haste II. So if you already have Haste III, obviously nothing's gonna happen.

Why not make it additive instead of a sent value? Just feels like a waste to make it even in vanilla, yea you get haste 2 all the time, but by the time you get enough netherite to want to make it chances are you have a beacon, which most will lug around for the haste 4.

**Comment by glisco03** [comment]
> Yea you get Haste II all the time. 

Well that's the point. You don't have to carry around a beacon, and just instamining everywhere is a big deal.

Also making it additive is nigh-impossible to get right and bug-free and also the difference between Haste II and IV ist negligible at best

**Comment by deadspidervenom** [comment]
Hmm how about a confit option that lets you change the haste level, or if
you want to go the extra mile compatibility with origins that if detected
they have a haste => 2 it upgrades the haste too 4.

**Comment by glisco03** [comment]
The newest build (0.2.2) replaces haste with a new effect called momentum, which works exactly the same apart from that it doesnt give you faster attack speed. Momentum can stack with haste, although beacons will not give you haste anymore when you have momentum under default conditions. This, and the momentum level can be configured now
