### ISSUE TITLE
Can't equip Hades Crystal 1.19

### ISSUE THREAD

**Issue by Thr4ckerzod** [glisco03/things#44]

**Comment by gliscowo** [comment]
Without any further context it's basically impossible for us to track this problem down. Primarily we would need your `latest.log` file - that should contain all the information we need
Cheers

**Comment by Thr4ckerzod** [comment]
[latest.log](https://github.com/wisp-forest/things/files/9176255/latest.log)

Im using the Medival Minecraft Modpack Fabric version

**Comment by gliscowo** [comment]
This is a known issue, it's caused by Bewitchment Plus declaring a missing item for the Necklace slot and thereby breaking all necklaces. Your only option right now is to remove Bewitchment Plus and wait for an update - they already have this fixed in their repo.
Cheers

**Comment by Thr4ckerzod** [comment]
Thank you
