### ISSUE TITLE
things and trinkets causing error 143 

### ISSUE THREAD

**Issue by kalethemonster** [glisco03/things#45]
(also posted to trinkets github)
im running a personal vanilla + world and decided to add a few more mods and saw things which i havent used in a while, and after installing, minecraft would not open with things and trinkets installed, and it didnt show the fabric startup error screen. each time i force quit java from activity monitor (im stuck with using a mac atm dont judge) it came up with error 143.

my mod list (exept for trinkets and things) is additional additions, auth me, axolotl bucket fix(aka axolotol item fix), better biome blend, better tridents, broken nametags, cit resewn, cloth config, detail armor bar, dynamic fps, echoes of the past, edit sign, fabric language koltin, fancy spore blosoms, forge config api port(used by the puzzles lib), global datapack, grind enchants, iris, damb dynam lights, litematica, mali lib, map atlas, more axolotl variants, mending tools dont break, meowing, midnight lib, more metal bars, patchouli, pehkui, petowner, pattable, phosphor, plasmo voice, puzzles lib, sodium+sodium extra, this rocks, variant crafting tables, variant barrels, and variant stick and stuff. they are all in their current versions and working as i type this.

**Comment by gliscowo** [comment]
It's close to impossible to deduce the problem with only the information you posted. We need at the very least your game's full log from a time this happens. To get that, launch your game and have it get stuck. Then go to the `logs` folder in `.minecraft` and send us the `latest.log` file
Cheers

**Comment by kalethemonster** [comment]
[latest.log](https://github.com/wisp-forest/things/files/9546218/latest.log)
this is from trying to open the game with only the fabric api, things and trinkets, the necessary depenancies, and then sodium (+sodium extra and RSO) because my mac needs those to run minecraft anyway. i once again had the issue.
i waited over 5 minutes for the game to open before terminating the process, it usually opens within 3

**Comment by Noaaan** [comment]
I think I know the issue. You do not have owo-lib installed.
Normally it should open up a window with sentinel, a small mod that lets you download it on the press of a button. Unfortunately, It seems that it currently does not work correctly on MacOS. 
You should be able to launch by installing the latest version

**Comment by kalethemonster** [comment]
> I think I know the issue. You do not have owo-lib installed. Normally it should open up a window with sentinel, a small mod that lets you download it on the press of a button. Unfortunately, It seems that it currently does not work correctly on MacOS. You should be able to launch by installing the latest version

thankyou, they really need to fix that on mac. i am a windows user who is forced to use mac atm due to my good computer getting broken by someone else, so i am a little lost on things.
