### ISSUE TITLE
Gleaming ore not Genereting 

### ISSUE THREAD

**Issue by JustLeicer** [glisco03/things#47]
The Gleaming ore is not generating, i am playing OccultCraft and added this mod, but the ore is not generating. (things-0.2.20+1.19.jar)

**Comment by Noaaan** [comment]
Things is not a Forge mod. You can not use it in a Forge modpack

**Comment by JustLeicer** [comment]
@Noaaan > Things is not a Forge mod. You can not use it in a Forge modpack

i know, OccultCraft is a fabric modpack

**Comment by Noaaan** [comment]
If you added this mod *after* creating your world, then you will not find Gleaming Ore in those chunks. New world-generation only applies on new chunks.

**Comment by JustLeicer** [comment]
@Noaaan yeah, i know. i generated new chunks and it did not spawn, i also check in 2 new worlds using spectator + xray and not a single one after searching for 1 hour per world.

**Comment by Ibaudia** [comment]
I am also experiencing this issue with BYG world generation. There is no gleaming ore in the world. I generated the world with Things already installed.

**Comment by Ibaudia** [comment]
You can see this issue by using my pack on Modrinth if you need to reproduce it. Sherman's Adventure Pack. That might help diagnose any issues, it could be a result of some other mod besides OTBYG but so far I haven't been able to correct the issue without changing that mod.

**Comment by gliscowo** [comment]
![2022-11-27_19 24 12](https://user-images.githubusercontent.com/15788224/204153094-b8f486d2-4e04-452b-b37e-b65f27fdbf15.png)
@Ibaudia 

After booting up an instance of your modpack and creating a world, I basically instantly found some Gleaming Ore. I did this experiment multiple times in different worlds and modpack versions and couldn't replicate the issue

Could your elaborate a bit further what your specific setup is?

**Comment by gliscowo** [comment]
Given that this issue has not proven reproducible and was now stale for 2 months, I will go ahead and close it. If the problem persists, please reopen it

Cheers
