### ISSUE TITLE
Compatibility with REI (GUI is in the way)

### ISSUE THREAD

**Issue by queenielawrens** [glisco03/things#5]
When using the displacement tome, REI covers the text field for new points (see image). Can you either make it so the text field is within the displacement tome box? Or, if that doesnt work, a config option to move it to the left side?

![2021-07-30_07 05 01](https://user-images.githubusercontent.com/67487848/127650649-fc7e2e73-2262-466d-9afa-1c0c497ee1aa.png)

**Comment by glisco03** [comment]
Eyo, thanks for reporting this!
I have actually never thought about this before, but it's an easy fix. I'll add a simple REI plugin that tells it to duck when the box is visible. Update should come within a a few days
Cheers

**Comment by gliscowo** [comment]
Fixed in 0.2.3
