### ISSUE TITLE
[Request[ EMI support for 1.18.2/1.19.2 for Sock recipes

### ISSUE THREAD

**Issue by ConqAra** [glisco03/things#50]
The Jumping Boost / Greater Speed Socks are not present as crafting recipes when using EMI.

**Comment by Dragon-Seeker** [comment]
There is no current support for EMI and there are no plans that I know of for such support. Please Refer to the statement made within [Conjuring Issue](https://github.com/wisp-forest/conjuring/issues/43) that outlines glisco's reasoning.
