### ISSUE TITLE
Awarded Infernal Scepter advancement upon other item losing durability

### ISSUE THREAD

**Issue by ObrenTune** [glisco03/things#56]
I tested this a few times to make sure it wasn't a fluke, but it seems that the durability changing on any other item you have awards you the achievement regardless

**Comment by gliscowo** [comment]
You did not give us enough information to be able to properly assist you. Namely:
 - What version of Things?
 - Any other mods? If so, what is your mod list?
 - Which modpack, if any?

**Comment by ObrenTune** [comment]
Apologies about that, anyway heres a run down of my current mods:
Currently running 1.19.2 of Minecraft

Current mods, and I am not playing with any premade modpack.

Things v0.2.200+1.19

Trinkets v3.4.1

Patchouli v1.19.2-77-FABRIC

owo-lib-0.9.3+1.19

charm-fabric-1.19.2-4.4.4

Hopefully this helps!

**Comment by gliscowo** [comment]
Thanks for reporting this, it has since been fixed in [release 0.3.0](https://modrinth.com/mod/things/version/0.3.0%2B1.19)
Cheers
