### ISSUE TITLE
Crashes when using displacement tome

### ISSUE THREAD

**Issue by Zwanzen** [glisco03/things#57]
[crash-2023-02-04_07.21.53-client.txt](https://github.com/wisp-forest/things/files/10607886/crash-2023-02-04_07.21.53-client.txt)

Crash report.

**Comment by gliscowo** [comment]
Upgrade [owo-lib](https://modrinth.com/mod/owo-lib), ideally to [0.9.3](https://modrinth.com/mod/owo-lib/version/0.9.3+1.19)
