### ISSUE TITLE
Update the wiki to add socks

### ISSUE THREAD

**Issue by TheRealPower** [glisco03/things#58]
Currently, socks aren't on the wiki and I can't find how to upgrade them or if that's been implemented yet, pls update sanku

**Comment by gliscowo** [comment]
Thanks for reminding me that this repository has a wiki - I totally forgot this exists. You should be looking at https://guides.wispforest.io/things/trinkets/socks/ which has up-to-date information.

Our hosted guides are also just web-versions of the in-game guidebooks - in the case of Things this is the **Things Almanac** you can craft with a **Book** and an **Apple**

Cheers

**Comment by TheRealPower** [comment]
Oh thank you! The modpack Im using doesn't add patchouli by default for some reason so I never ended up actually using the almanac, you should probably update the wiki link on the curse forge page to include the more updated wiki link
