### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by wsxiya** [glisco03/things#59]
Can you add the recipe for socks for jei，When using jei, I found that there is no jie formula for upgrading socks

**Comment by gliscowo** [comment]
While I do understand that not everyone wishes to use REI, the vast majority of modpacks and players do - and as such it is not in my interest to maintain the additional development burden attached to supporting an entirely separate (and, in my humble opinion, inferior) recipe viewer. I would recommend you try out REI in either case, as it is generally more supported throughout the Fabric landscape

Cheers

**Comment by wsxiya** [comment]
Thank you, I understand that rei is better, I personally like rei very much, but rei will crash in my 300+ mod integration pack, so I chose jei, I am very sorry to bother you, thank you
