### ISSUE TITLE
BetterCombat Compatibility

### ISSUE THREAD

**Issue by ereese99** [glisco03/things#60]
The arm extender is not compatible with any weapon that uses Bettter Combat mechanics

**Comment by BasiqueEvangelist** [comment]
As far as I know, [Better Combat deliberately isn't compatible with Reach Entity Attributes](https://github.com/ZsoltMolnarrr/BetterCombat/issues/49#issuecomment-1218208250), which is what the Arm Extender (and some other mods) use to modify reach.

Plus, there's this bit from the Better Combat FAQ.
![изображение](https://user-images.githubusercontent.com/72868417/226428024-bb216e9b-c5b0-456f-951b-f815a1e807a9.png)

**Comment by gliscowo** [comment]
As explained by BasiqueEvangelist above, this is not something we will fix - it's intended behavior by Better Combat after all. If you still like this to work, you may want to open an issue on their side and maybe ask about a config option

Cheers
