### ISSUE TITLE
[Feature Request] Ability to disable Retribution enchantment

### ISSUE THREAD

**Issue by BernardoGrigiastro** [glisco03/things#61]
Title says it all i guess, thx

**Comment by gliscowo** [comment]
Why would you like to see this implemented? We generally don't do feature toggles like these, so you need to explain your specific use-case further.

Cheers

**Comment by BernardoGrigiastro** [comment]
Well... it is absolutely useless to me as i never use shields so its just taking other enchants weight (if i understand enchants right :) ) AND what a weight, its on about 60/70% of my fishing loot, thx for the quick reply

**Comment by gliscowo** [comment]
I haven't been able to reproduce the weight problem you mentioned in my testing. What modpack are you playing, if any? Generally, it might be advisable to send us your `latest.log` to try and figure out why Retribution is seemingly weighted so heavily

As for the toggle, I'm afraid this isn't really a good reason to implement one - if the weight issue wasn't occurring (which seems to be related to your setup specifically), you could simply go and ignore that the enchantment even exists

Cheers

**Comment by gliscowo** [comment]
Given that this issue has now been stale for over two months, I'll go ahead and close it. If you still want to look into it further, feel free to reopen it as you see fit

Cheers
