### ISSUE TITLE
Displacement Magic cannot be charged with the Ender Pearl

### ISSUE THREAD

**Issue by yuchen-guts** [glisco03/things#63]
Displacement Magic cannot be charged with the Ender Pearl

**Comment by gliscowo** [comment]
What exactly was it that you were trying to do? In recent versions of the mod, you charge the Displacement Tome by right-clicking it onto Ender Pearls in your inventory, in older builds you have to shift-right-click the item while holding it

I hope this answers your question
Cheers

**Comment by gliscowo** [comment]
Given that this issue has now been stale for almost two months, I'll go ahead and close it. If you have more insight to give, please feel free to reopen it

Cheers
