### ISSUE TITLE
can't join multiplayer, missing a bunch of tags?

### ISSUE THREAD

**Issue by temyy** [glisco03/things#68]
happens with owo lib 0.11.0 and things 0.3.1, both mods work just fine in a singleplayer world but as soon as i try joining a server that has those mods i get kicked with "connection lost %s". server log just says player disconnected but client log points to a bunch of missing tags
ive had a similar issue with betterend and its dependency bclib, but never figured out the cause for this
client log https://paste.atlauncher.com/view/fe63915c-50bc-4322-9c62-a645297b5e9a
server log attached as file
[latest.log](https://github.com/wisp-forest/things/files/12135360/latest.log)

**Comment by Noaaan** [comment]
This is actually a bug with Quilt Standard Libraries, and should be fixed by this pull request: https://github.com/QuiltMC/quilt-standard-libraries/pull/326
I am not sure exactly what triggers the issue, but this is generally not something we can solve at this time.

**Comment by TropheusJ** [comment]
Given that PR fixes a bug with a quilt-specific API, I don’t think it’s related.

**Comment by TropheusJ** [comment]
Looked at the server log, definitely unrelated.

**Comment by gliscowo** [comment]
Even in that case, I believe the chance of this being caused by Things to be *extremely* slim and would suspect some kind of Quilt problem either way
