### ISSUE TITLE
Recipe for Empty Agglomeration missing when playing DarkRPG - RPG Quest Magic & Origins Online Adventure

### ISSUE THREAD

**Issue by distingusa** [glisco03/things#69]
Hey!

Love your "Things" mod in the DarkRPG pack! However, I noticed the recipe for "Empty Agglomeration" is missing. Any chance this could be addressed? Thanks!

**Comment by BasiqueEvangelist** [comment]
...you sure that pack didn't just remove that recipe? Not all modpack makers want the agglomeration to be craftable

**Comment by Noaaan** [comment]
That is very likely on DarkRPGs side. They have in the past disabled multiple items for their server. Please check your configs/datapacks or ask in their Discord server first.

**Comment by gliscowo** [comment]
As I would also presume that this is simply DarkRPG's configuration and thus not a Things issue, I'll go ahead and close this
