### ISSUE TITLE
Guide is unclear about upgrading socks

### ISSUE THREAD

**Issue by ryleu** [glisco03/things#70]
The guide section on socks is impossible to understand. It should probably be a lot more clear how to upgrade them and how to combine items, beyond just "in a crafting table :D".

**Comment by Noaaan** [comment]
You do not even need a crafting table. It's a shapeless recipe that takes in one gleaming powder, socks, and one Strong Swiftness Potion (Potion of Switness II). 
Could you be more precise why that part of the guide is confusing you? I.E. if its due to the lack of images.

**Comment by ryleu** [comment]
I think images would help, but if you said what you just said in the book, it'd help. Saying exactly that would make it much less confusing. It also says "String Swiftness Potion", not "Strong", which is part of my confusion.
