### ISSUE TITLE
Arm Extender

### ISSUE THREAD

**Issue by Huangxigua** [glisco03/things#72]
description says an additional 2 blocks of reach (+2 Reach, +2 Attack Range) but it does not seem to extend the reach of my weapons (placing blocks/breaking blocks has extra reach though) 

https://github.com/wisp-forest/things/assets/142184605/866af349-ae43-44dd-883c-b0c110ff9b12

**Comment by BasiqueEvangelist** [comment]
Better Combat explicitly doesn't support increasing attack range.
![изображение](https://github.com/wisp-forest/things/assets/72868417/d3501562-ea0b-43fb-b0a7-6ecadb95ec1f)

**Comment by Huangxigua** [comment]
ohh ic that makes sense ty!
