### ISSUE TITLE
game crashes when clicking empty agglomeration in inventory

### ISSUE THREAD

**Issue by ryleu** [glisco03/things#78]
mods:
![image](https://github.com/wisp-forest/things/assets/69326171/ef54448f-2c5b-416b-9e80-ab130846604e)

crash log:
https://mclo.gs/Ntsecvz

other related info:
![image](https://github.com/wisp-forest/things/assets/69326171/2054eb15-799a-463e-a73d-9c444d816cf3)

**Comment by ryleu** [comment]
also occurs when right clicking in-game

**Comment by gliscowo** [comment]
@Dragon-Seeker, since you implemented this functionality - could you maybe take a look and investigate this?
