### ISSUE TITLE
agglomeration cannot be crafted with other items at all

### ISSUE THREAD

**Issue by ryleu** [glisco03/things#79]
![image](https://github.com/wisp-forest/things/assets/69326171/315bb934-469f-489a-823f-e9318230a29b)

**Comment by Dragon-Seeker** [comment]
That is the already crafted version. Such is permanent with no way of changing or adjusting such after the fact

**Comment by gliscowo** [comment]
Given both the correct statement above which mostly invalidates this anyway and the lack of a response, I'll go ahead and close this as invalid

Cheers

**Comment by ryleu** [comment]
huh, i must've given myself an agglomeration instead of an empty agglomeration, my apologies
