### ISSUE TITLE
Incompatible with Modern Industrialization

### ISSUE THREAD

**Issue by JMackey1** [glisco03/things#80]
I think this issue is related; https://github.com/wisp-forest/things/issues/74

I also isolated the issue down to the Things mod, and not owo lib. In Modern Industrialization, when you hold a wrench and are looking at a multiblock piece, it it supposed to show a "hologram" of the multiblock structure. It does not display at all with Things enabled - disabling Things, and making no other changes, causes the hologram to appear.

Happens with or without Indium/Iris/Sodium enabled.

Minecraft 1.20.1, Fabric Loader 0.14.22, Fabric API 0.89.0+1.20.1

**Comment by gliscowo** [comment]
Which version of owo-lib were you running when this problem occured? This feels like a problem that was resolved in [0.11.2](https://modrinth.com/mod/owo-lib/version/0.11.2+1.20)

**Comment by JMackey1** [comment]
0.11.2+1.20

**Comment by gliscowo** [comment]
Hmm right, in that case I'll investigate this myself, thanks for responding so quickly

**Comment by JMackey1** [comment]
I decided to test this again after various other mod updates, and it seems to be working correctly now. No idea which update did it, but it wasn't Things or owo-lib.

**Comment by gliscowo** [comment]
Given that the problem appears to be solved when running an up-to-date mod set, I'll go ahead and close this issue. Thanks for reporting either way!

Cheers
