### ISSUE TITLE
Incompatibility with Scannables

### ISSUE THREAD

**Issue by 923penguin** [glisco03/things#83]
Found that Scannables isn't working with Things. As in the pictures, Scannables will typically render an outline around found blocks, but with Things installed it fails to do so.
Only difference between the two screenshots is Things, no other mods changed, installed, or uninstalled.

![2023-11-24_19 18 05](https://github.com/wisp-forest/things/assets/76225112/d9ab9866-0d5d-4954-93f3-300d7ea3e0bc)
![2023-11-24_19 17 27](https://github.com/wisp-forest/things/assets/76225112/f88862ba-9b40-4b1a-9968-06dc53014e76)

Running on MC 1.20.1, Fabric 0.14.24. 
Modlist is:
Architectury (9.1.12)
Fabric API (0.90.7)
Forge Config API Port (8.0.0)
owo (0.11.2)
Scannable (1.7.12)
Things (0.3.1 + 1.20)

**Comment by gliscowo** [comment]
This was fixed as of [0.3.3](https://modrinth.com/mod/things/version/0.3.3+1.20.3), thanks for reporting
Cheers
