### ISSUE TITLE
Toggling Jumpy on Socks has no ingame instruction

### ISSUE THREAD

**Issue by winderine** [glisco03/things#84]
> Toggling Jumpy on socks is done by sprinting while sneaking. It is detailed in the Things guide

_Originally posted by @Noaaan in https://github.com/wisp-forest/things/issues/40#issuecomment-1166611327_

I literally asked my server admin team to find out why my jumpy socks have never had jump boost. They didn't know off the top of their heads because it had just worked for them. This is frustrating.

1. this *toggles*??? That's cool but why was it disabled by default?? 
2. the guide is not available ingame and the tiny gray arrow that looks exactly like the tiny green arrow on the jumpy socks in JEI being such a subtle indication of this feature meant that I had no reason to go out of my way to find and explore yet another mods wiki
3. According to said website, I need to shift while sprinting for a whole second to toggle this, but it doesn't tell you that sparkles will appear and the tiny gray arrow in the tooltip turns green when you did so successfully
4. sometimes you get the sparkles without successfully toggling the socks even if you hold it for a long time
5. It doesn't seem to work just to press sprint and sneak at the same time, you actually have to be moving, so for those of us with motor control difficulties is there some way to change this keybind?
6. "Step assist" also being mildly annoying at times, is there a way to disable that?

**Comment by BasiqueEvangelist** [comment]
> the guide is not available ingame

It is, though? Unless you have one of the Things versions where Patchouli is disabled, the Things Almanac should be accessible

**Comment by gliscowo** [comment]
Now, this is indeed explained in the Things Almanac. However, it is also no longer relevant since the [latest Things release](https://modrinth.com/mod/things/version/0.3.2+1.20.2) changes this behavior to use a keybind instead

As such, I'll go ahead and close this
Cheers
