### ISSUE TITLE
Make Bater Wuckets also act like empty buckets

### ISSUE THREAD

**Issue by dekub100** [glisco03/things#85]
Hey just noticed I cant really pick up the water i placed with the Bater Wucket, so I think this could make for a cool feature **if possible**.

To explain the title further:
Make Bater Wuckets act like empty buckets when right clicking the air (or something similar to that) so you can also pick up that water.

**Comment by thcrt** [comment]
+1, this would be really useful

**Comment by gliscowo** [comment]
I agree that this is rather useful, in fact it's been on my list for a long time. I've now implemented it in the form of the separate **Bempty Ucket** (which acts like an infinite empty bucket for *any* fluid) in [0.3.4 for 1.20.3+](https://modrinth.com/mod/things/version/0.3.4+1.20.3)

Cheers
