### ISSUE TITLE
Option to disable Recall Potion recipe

### ISSUE THREAD

**Issue by WerDei** [glisco03/things#86]
I could not remove only the brewing recipe using other mods, and had to disable the item entirely (using Item Obliterator). This is not a perfect dolution, since the recipe still works and wastes an enderpearl. I also cannot add the potion to loottables now, to turn it into a unique and finite resource. Adding an option to disable the brewing recipe would solve these issues. 

Alternatively, you can add an option to change the item used to brew the potion. This way modpack makers will be able to not only disable, but make the recipe more or less expensive as well.

**Comment by gliscowo** [comment]
Hey, thanks for your suggestion! This has now been implemented in [0.3.4 for 1.20.3+](https://modrinth.com/mod/things/version/0.3.4+1.20.3)

Cheers
