### ISSUE TITLE
remove recall potions craft and socks upgrades. 

### ISSUE THREAD

**Issue by Kisuny** [glisco03/things#91]
Pls add way to remove recall_potion and socks upgrades.

To make it easier for modpack creators to change the balance of your mod.

Thing version: things-0.3.0+1.19
MC version: 1.19.2

**Comment by gliscowo** [comment]
As for the Recall Potion, I'm afraid you're simply on too old of a version - this was implemented recently in [0.3.4 for 1.20.3+](https://modrinth.com/mod/things/version/0.3.4+1.20.3). Sadly, 1.19.2 has long passed its support window and this change will not be backported.

In regards the Socks upgrades, this is actually a normal recipe (located under `things:sock_upgrade_crafting`) which you should be able to remove using standard recipe removal methods

Cheers
