### ISSUE TITLE
com.glisco.things.misc.ThingsConfig missing from the misc folder

### ISSUE THREAD

**Issue by HojoTimberwolf** [glisco03/things#92]
I am trying to implement a nether pouch using the nether-chest mod. The idea is an end pouch but with the nether-chest opening.

I am currently trying to extend all the classes but as I am having difficulty with this so my second pass is to just get it working by forking the Things mod and adding new code.

I noticed when following downloading the repo that the ThingsConfig file is missing and that without it, I cannot compile and run minecraft.

please update the Repo to include the ThingsConfig

**Comment by Noaaan** [comment]
You are misunderstanding how Things config works. It is a part of owo-config (owo-lib). It is driven by an annotation processor, and the configuration code is generated at build/compile time. Some details on the usage is described here: https://docs.wispforest.io/owo/config/getting-started/

If you have owo-lib declared in your `build.gradle` file then you want to enable the annotation processor as described

```gradle
dependencies {
    annotationProcessor modImplementation("io.wispforest:owo-lib:${project.owo_version}")
}
```

If you are just including Things alone then I am unsure on how you want to properly build against it. It might be enough to just use `annotationProcessor` and `modCompileOnly` in the buildscript instead, like so:

```gradle
dependencies {
    annotationProcessor modCompileOnly("io.wispforest:owo-lib:${project.owo_version}")
}
```

That way the code might generate correctly, and you would not need to include owo in any way.

**Comment by gliscowo** [comment]
Given that this issue seems to stem from your lack of familiarity with owo-config (as pointed out by Noaaan), I'll close this as Not Planned for now

Cheers
