### ISSUE TITLE
Option to disable Hardening Catalyst or make a blacklist

### ISSUE THREAD

**Issue by Aruman-Zen** [glisco03/things#93]
Hello!
I'm making a modpack and some mods have items that are strong but have very low durability, the problem is that with this item you can make some items too strong, i was asking as the title says, an option to disable the Hardening Catalyst or make a blacklist where i could put specific items in, that way it can have more compatibility with some mods.

**Comment by gliscowo** [comment]
There is already a blacklist - simply put items you don't want the hardening catalyst to apply to into the `things:hardening_catalyst_blacklist` item tag. Additionally, if you want to disable it completely, you could just remove the catalyst's recipe - there is no other way to obtain it

Cheers
