### ISSUE TITLE
More reach with "longer" weapons (Better Combat) and Arm Extender

### ISSUE THREAD

**Issue by ihymyly** [glisco03/things#98]
Currently, increasing the user's does not work with multiple reach-increasing buffers. Chakrams from Simply Swords will not have increased attacking range. Since a majority of these weapons have a reach modifier themslves, letting the Arm Extender further increase it would be a nice change.

**Comment by BasiqueEvangelist** [comment]
Doesn't Better Combat explicitly disallow changing the reach? (#72)

**Comment by ihymyly** [comment]
Wasn't aware of this despite searching for the cause.
